#pragma once
#include <Windows.h>

namespace OpenLGP
{
	public enum class Keys : int
	{
		A = (int)'A',
		B = (int)'B',
		C = (int)'C',
		D = (int)'D',
		E = (int)'E',
		F = (int)'F',
		G = (int)'G',
		H = (int)'H',
		I = (int)'I',
		J = (int)'J',
		K = (int)'K',
		L = (int)'L',
		M = (int)'M',
		N = (int)'N',
		O = (int)'O',
		P = (int)'P',
		Q = (int)'Q',
		R = (int)'R',
		S = (int)'S',
		T = (int)'T',
		U = (int)'U',
		V = (int)'V',
		W = (int)'W',
		X = (int)'X',
		Y = (int)'Y',
		Z = (int)'Z',
		Plus = (int)VK_OEM_PLUS,
		Minus = (int)VK_OEM_MINUS,
		Space = (int)VK_SPACE,
		One = (int)'1',
		Two = (int)'2',
		Three = (int)'3',
		Four = (int)'4',
		Five = (int)'5',
		Six = (int)'6',
		Seven = (int)'7',
		Eight = (int)'8',
		Nine = (int)'9',
		Zero = (int)'0',
		Escape = (int)VK_ESCAPE,
		Cancel = (int)VK_CANCEL,
		Enter = (int)VK_RETURN,
		Shift = (int)VK_SHIFT,
		Control = (int)VK_CONTROL,
		CapsLock = (int)VK_CAPITAL,
		Pause = (int)VK_PAUSE,
		Alt = (int)VK_MENU,
		End = (int)VK_END,
		Insert = (int)VK_INSERT,
		Delete = (int)VK_DELETE,
		Down = (int)VK_DOWN,
		Left = (int)VK_LEFT,
		Right = (int)VK_RIGHT,
		Up = (int)VK_UP
	};
}